protected/controllers/SampleController.php
<?php

class SampleController extends RController
{
	/**
	* @return array action filters
	*/
	public function filters()
	{
		return array(
			'rights', // perform access control using Rights for CRUD operations
		);
	}

	public function allowedActions() {
		return 'index';
	}

	public function actionIndex()
	{
		$this->render('index');
	}

	public function actionInfo()
	{
		$this->render('info');
	}

	public function actionPage()
	{
		$this->render('page');
	}
}

protected/views/sample/index.php
<?php
/* @var $this SampleController */

$this->breadcrumbs=array(
	'Sample',
);
?>
<h1><?php echo $this->id . '/' . $this->action->id; ?></h1>

<p>
	You may change the content of this page by modifying
	the file <tt><?php echo __FILE__; ?></tt>.
</p>

<p>This page shows availability of Rights, the Authentication manager modules created by Christoffer Niska <code>cniska@live.com</code>.</p>

<p>If you are admin, please <?php echo CHtml::link('click here', array('/sample/page')); ?>.</p>
<p>If you are authenticated user, please <?php echo CHtml::link('click here', array('/sample/info')); ?>.</p>

<hr/>
<p>You are login using: <strong><?php echo Yii::app()->user->name; ?></strong> with ID (<?php echo Yii::app()->user->Id; ?>)</p>
<p>Are you guest? <code><?php echo (Yii::app()->user->isGuest) ? "Yes" : "No"; ?></code>

<?php if(!Yii::app()->user->isGuest): ?>
<p>User assigned role(s): 
<?php
	$roles = Rights::getAssignedRoles();
	foreach($roles as $role) echo "<code>" . $role->name . "</code>";
?>
</p>
<?php endif; ?>

protected/views/sample/info.php
<?php
/* @var $this SampleController */

$this->breadcrumbs=array(
	'Sample'=>array('/sample'),
	'Info',
);
?>
<h1><?php echo $this->id . '/' . $this->action->id; ?></h1>

<p>
	You may change the content of this page by modifying
	the file <tt><?php echo __FILE__; ?></tt>.
</p>
<p>
	Please note that this page is accessisble by <code>authenticated</code> user only.
</p>
<p>You are login using: <strong><?php echo Yii::app()->user->name; ?></strong> with ID (<?php echo Yii::app()->user->Id; ?>)</p>
<p>You have following roles:
<?php
	$roles = Rights::getAssignedRoles(Yii::app()->user->Id);
	foreach($roles as $role) echo "<code>" . $role->name . "</code>";
?>
</p>

protected/views/sample/page.php
<?php
/* @var $this SampleController */

$this->breadcrumbs=array(
	'Sample'=>array('/sample'),
	'Page',
);
?>
<h1><?php echo $this->id . '/' . $this->action->id; ?></h1>

<p>
	You may change the content of this page by modifying
	the file <tt><?php echo __FILE__; ?></tt>.
</p>
<p>
	Please note that this page is accessisble by <code>authenticated & admin</code> user only.
</p>
<p>You are login using: <strong><?php echo Yii::app()->user->name; ?></strong> with ID (<?php echo Yii::app()->user->Id; ?>)</p>
<p>You have following roles:
<?php
	$roles = Rights::getAssignedRoles(Yii::app()->user->Id);
	foreach($roles as $role) echo "<code>" . $role->name . "</code>";
?>
</p> 